name: mod-build
on:
  push
jobs:
  clone:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
  build:
    runs-on: ubuntu-20.04
    steps: 
    - run:
          sh ./start.sh
    needs: clone
