name: mod-build
on:
  push
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/MaxSaleh/ArcaneArteries/archive/refs/heads/master.zip
      Pack_Name: master
      Open_Pack_Name: ArcaneArteries-master
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: 11
        java-package: jdk
    - run: 
        sh ./start.sh
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: /opt/libs/
