name: mod-build
on:
  push
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v2
      uses actions/checkout@master
    - name build
        run |
          sh ./use/start.sh
