name: mod-build
on:
  push
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/KELETU66666/Hardcore-Ender-Expansion-2/archive/refs/heads/wip.zip
      Pack_Name: wip
      Open_Pack_Name: Hardcore-Ender-Expansion-2-wip
    steps:
    - uses: actions/checkout@v2
    - run: 
        sh ./start.sh
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: /opt/libs/
